#ifndef APP_RESOURCES_H_
#define APP_RESOURCES_H_

#define IDI_APP_ICON 101
#define IDI_TRAY_ICON 102
#define IDB_QS_LOGO 103
#define IDB_ICON_MORE_VERT 104
#define IDB_ICON_REFRESH 105

#endif  // APP_RESOURCES_H_
